### ISSUE TITLE
Writing support for the python library

### ISSUE THREAD

**Issue by jmpfar** [facebookresearch/pyvrs#40]
---

## 🚀 Feature

Please add writing support for the python library

## Motivation & Examples

Although I am planning to write C++ code for most of the write part, I want the processing code that will convert the VRS file between image formats be written in python. Currently, it looks like this code [exists but isn't open sourced](https://github.com/facebookresearch/pyvrs/blob/fea3aa727120e57167f8fd24b60f00455803249c/csrc/Pybind11.cpp#L54). It'd be great if you could open source it as well to make this library/format more useful.

**Comment by georges-berenger** [comment]
Thanks for the feedback.
We don't have a 100% C++ free VRS file generation code path, even internally, in large part because by design, we want to force that you can't have two definitions of file structures (aka "datalayout" in particular), one in Python and one in C++. So all datalayout definitions must be done in C++, and the writer code you're pointing to allows us to publish C++ stream definitions that the python code can request by name. We currently have no plans to open source that part, as it requires changing pyvrs for each distinct file format definitions, so it can't go in pip for instance.
We have conversation about adding image filtering, but we have no ETA at this point.
